# Generated by Django 3.1.7 on 2021-04-01 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertReceivingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='alert receiving group')),
                ('remarks', models.CharField(max_length=200, verbose_name='group marks')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='rule group name')),
                ('remarks', models.CharField(max_length=200, verbose_name='rule group remarks')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='rule name')),
                ('rule', models.CharField(max_length=250, verbose_name='alert rule')),
                ('check_period', models.IntegerField(verbose_name='rule check time period')),
                ('labels', models.CharField(max_length=250, verbose_name='alert labels')),
                ('summary', models.CharField(max_length=250, verbose_name='alert summary')),
                ('description', models.CharField(max_length=250, verbose_name='alert description')),
                ('level', models.IntegerField(choices=[(0, 'general'), (1, 'medium'), (2, 'serious')], default=0, verbose_name='server status')),
                ('user', models.CharField(max_length=100, verbose_name='create user')),
                ('remarks', models.CharField(max_length=100, verbose_name='rule mark')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='version create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='deploy or update time')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_group', to='rule.rulegroup', verbose_name='rule group')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RulesTAlertUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_user_for_rules', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_users', to='rule.rules')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RulesTAlertGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_group_rules', to='rule.alertreceivinggroup')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_groups', to='rule.rules')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RuleGroupTAlertUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_user_for_rule', to=settings.AUTH_USER_MODEL)),
                ('rule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_users', to='rule.rulegroup')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RuleGroupTAlertGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_group_rule', to='rule.alertreceivinggroup')),
                ('rule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_groups', to='rule.rulegroup')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlertGroupTUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_user_group', to='rule.alertreceivinggroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
