# Generated by Django 3.1.7 on 2021-04-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='alert_period',
            field=models.IntegerField(default=5, verbose_name='alert send time period minute'),
        ),
    ]
