# Generated by Django 3.1.7 on 2021-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto_20210426_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='status',
            field=models.IntegerField(choices=[(0, 'enable'), (1, 'Disable')], default=0, verbose_name='if Disable'),
        ),
    ]
