# Generated by Django 3.1.7 on 2021-03-31 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=100, verbose_name='alert name')),
                ('alert_id', models.IntegerField(verbose_name='alert id')),
                ('trigger_time', models.DateTimeField(auto_now_add=True, verbose_name='alert trigger time')),
                ('resolved_time', models.DateTimeField(verbose_name='alert resolved time')),
            ],
        ),
        migrations.CreateModel(
            name='SendRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'general'), (1, 'medium'), (2, 'serious')], default=0, verbose_name='server status')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_send', to='alert.alertrecords')),
                ('alert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AckRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack', models.IntegerField(choices=[(0, 'yes'), (1, 'no')])),
                ('ack_mark', models.CharField(max_length=200, verbose_name=' ack commit')),
                ('ack_time', models.DateTimeField(auto_now_add=True, verbose_name='ack time')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_ack', to='alert.alertrecords')),
            ],
        ),
    ]
