# Generated by Django 3.1.7 on 2021-03-31 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrecords',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='send alert time'),
            preserve_default=False,
        ),
    ]
