# Generated by Django 3.1.7 on 2021-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20210331_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecords',
            name='host',
            field=models.CharField(default='', max_length=100, verbose_name='alert host'),
        ),
        migrations.AddField(
            model_name='alertrecords',
            name='if_send',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no')], default=0, verbose_name='if send alert'),
        ),
    ]
