# Generated by Django 3.1.7 on 2021-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_alertrecords_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1618227278, verbose_name='send alert time'),
        ),
    ]
