# Generated by Django 3.1.7 on 2021-04-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_auto_20210412_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecords',
            name='alert_uuid',
            field=models.CharField(default='', max_length=100, verbose_name='alert uuid'),
        ),
        migrations.AddField(
            model_name='alertrecords',
            name='fingerprint',
            field=models.CharField(default='', max_length=200, verbose_name='alert fingerprint'),
        ),
        migrations.AddField(
            model_name='alertrecords',
            name='if_send_resolved',
            field=models.IntegerField(choices=[(0, 'yes'), (1, 'no')], default=1),
        ),
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1618457709, verbose_name='send alert time'),
        ),
    ]
