# Generated by Django 3.1.7 on 2021-04-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_auto_20210415_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1618467827, verbose_name='send alert time'),
        ),
    ]
