# Generated by Django 3.1.7 on 2021-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0012_auto_20210426_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1619686260, verbose_name='send alert time'),
        ),
    ]
