# Generated by Django 3.1.7 on 2021-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0014_auto_20210429_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrecords',
            name='rule_id',
            field=models.IntegerField(verbose_name='rule id'),
        ),
        migrations.AlterField(
            model_name='alertrecords',
            name='status',
            field=models.IntegerField(choices=[(1, 'firing'), (2, 'resolved'), (3, 'delete'), (4, 'disable')], default=1, verbose_name='receiver type'),
        ),
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1623812367, verbose_name='send alert time'),
        ),
    ]
