# Generated by Django 3.1.7 on 2021-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0015_auto_20210616_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1623917030, verbose_name='send alert time'),
        ),
    ]
