# Generated by Django 4.1.7 on 2023-03-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0017_auto_20210617_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendrecords',
            name='level',
        ),
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1679621080, verbose_name='send alert time'),
        ),
    ]
