# Generated by Django 4.1.7 on 2023-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0018_remove_sendrecords_level_alter_sendrecords_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrecords',
            name='send_time',
            field=models.IntegerField(default=1679637268, verbose_name='send alert time'),
        ),
    ]
