# Generated by Django 4.1.7 on 2023-03-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpand',
            name='erp_id',
            field=models.CharField(default='186000000', max_length=30, verbose_name='user dongdong erp count'),
        ),
    ]
